name: mne1.4.2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.15.6
  - attr=2.5.1
  - autoreject=0.4.2
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - black=23.7.0
  - blosc=1.21.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.0
  - ca-certificates=2025.1.31
  - cached_property=1.5.2
  - cairo=1.16.0
  - cffi=1.15.1
  - cfitsio=4.2.0
  - chardet=5.1.0
  - charls=2.4.2
  - cloudpickle=2.2.1
  - conda=23.7.2
  - contourpy=1.1.0
  - cryptography=41.0.2
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - dicom2nifti=2.4.8
  - dipy=1.7.0
  - docutils=0.20.1
  - double-conversion=3.3.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.41.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - gdcm=2.8.9
  - gettext=0.21.1
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.76.4
  - glib-tools=2.76.4
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - h5py=3.9.0
  - harfbuzz=7.3.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - icu=72.1
  - imagecodecs=2023.7.10
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.0
  - ipython_genutils=0.2.0
  - jaraco.classes=3.3.0
  - jellyfish=1.0.0
  - json-c=0.16
  - jsoncpp=1.9.5
  - jupyter=1.0.0
  - jupyter_client=8.3.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
  - jxrlib=1.1
  - keyring=24.2.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lazy_loader=0.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libass=0.17.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang13=16.0.6
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdeflate=1.18
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran=3.0.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libmamba=1.4.9
  - libmambapy=1.4.9
  - libmatio=1.5.23
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libspatialindex=1.9.3
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.19.0
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp=1.3.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.4
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.40.1
  - loguru=0.7.0
  - lxml=4.9.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.9
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mne-base=1.4.2
  - mne-bids=0.12
  - mpg123=1.31.3
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbconvert-core=7.7.2
  - nbconvert-pandoc=7.7.2
  - ncurses=6.4
  - nettle=3.8.1
  - nibabel=5.1.0
  - nlohmann_json=3.11.2
  - nomkl=1.0
  - nspr=4.35
  - nss=3.89
  - numba=0.57.1
  - numexpr=2.8.4
  - numpy=1.24.4
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openmeeg=2.5.6
  - openssl=3.1.2
  - p11-kit=0.24.1
  - pandoc=3.1.3
  - pcre2=10.40
  - pillow=10.0.0
  - pixman=0.40.0
  - proj=9.2.1
  - prometheus_client=0.17.1
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pugixml=1.13
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pydicom=2.4.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pytables=3.8.0
  - python=3.11.4
  - python-fastjsonschema=2.18.0
  - python-lsp-server-base=1.7.4
  - python-tzdata=2023.3
  - python_abi=3.11
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtconsole-base=5.4.3
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - rpds-py=0.9.2
  - rtree=1.0.1
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - s2n=1.3.46
  - scikit-image=0.21.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn-base=0.12.2
  - secretstorage=3.3.3
  - sip=6.7.10
  - snappy=1.1.10
  - spyder=5.4.3
  - spyder-kernels=2.4.3
  - sqlite=3.42.0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - svt-av1=1.4.1
  - tbb=2021.9.0
  - tbb-devel=2021.9.0
  - tk=8.6.12
  - tornado=6.3.2
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - ujson=5.7.0
  - utfcpp=3.2.3
  - vtk=9.2.6
  - vtk-base=9.2.6
  - vtk-io-ffmpeg=9.2.6
  - watchdog=3.0.0
  - wrapt=1.15.0
  - wurlitzer=3.0.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.39
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.3
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.3
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.9.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - aiofiles==23.1.0
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - anyio==3.7.1
      - argon2-cffi==21.3.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.3
      - async-timeout==4.0.2
      - atomicwrites==1.4.1
      - attrs==23.1.0
      - autopep8==2.0.2
      - babel==2.12.1
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.5
      - beautifulsoup4==4.12.2
      - binaryornot==0.4.4
      - bleach==6.0.0
      - boltons==23.0.0
      - cached-property==1.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.2.0
      - click==8.1.6
      - colorama==0.4.6
      - colorspacious==1.1.2
      - comm==0.1.3
      - conda-package-handling==2.0.2
      - conda-package-streaming==0.8.0
      - cookiecutter==2.2.3
      - cycler==0.11.0
      - darkdetect==0.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - diff-match-patch==20230430
      - dill==0.3.7
      - docstring-to-markdown==0.12
      - edflib-python==1.0.7
      - eeglabio==0.0.2.post4
      - entrypoints==0.4
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - flake8==6.0.0
      - flit-core==3.9.0
      - future==0.18.3
      - graphql-core==3.2.3
      - h11==0.14.0
      - h2==4.1.0
      - h5io==0.1.8
      - hpack==4.0.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - hyperframe==6.0.1
      - idna==3.4
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipycanvas==0.13.1
      - ipyevents==2.0.1
      - ipykernel==6.24.0
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipyvtklink==0.2.2
      - ipywidgets==8.0.7
      - isort==5.12.0
      - jaraco-classes==3.3.0
      - jedi==0.18.2
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.0
      - json5==0.9.14
      - jsonpatch==1.32
      - jsonpointer==2.0
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-console==6.6.3
      - jupyter-events==0.6.3
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - lazy-loader==0.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mffpy==0.8.0
      - mistune==3.0.0
      - mne==1.4.2
      - mne-qt-browser==0.5.1
      - mne-rsa==0.9.1
      - more-itertools==10.0.0
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.7.2
      - nbformat==5.9.1
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nilearn==0.10.1
      - notebook==7.0.0
      - notebook-shim==0.2.3
      - numpydoc==1.5.0
      - openneuro-py==2023.1.0
      - overrides==7.3.1
      - packaging==25.0
      - pandas==2.3.0
      - pandas-flavor==0.7.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.1
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pingouin==0.5.5
      - pip==23.2.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.9.1
      - pluggy==1.2.0
      - ply==3.11
      - pooch==1.7.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pybv==0.7.6
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pydocstyle==6.3.0
      - pyflakes==3.0.1
      - pygments==2.15.1
      - pylint==2.17.4
      - pylint-venv==3.0.2
      - pyls-spyder==0.4.0
      - pymatreader==0.0.32
      - pyopengl==3.1.6
      - pyopenssl==23.2.0
      - pyparsing==3.0.9
      - pyqtgraph==0.13.3
      - pysocks==1.7.1
      - pysurfer==0.11.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-lsp-black==1.3.0
      - python-lsp-jsonrpc==1.0.0
      - python-lsp-server==1.7.4
      - python-picard==0.7
      - python-slugify==8.0.1
      - pytoolconfig==1.2.5
      - pytz==2023.3
      - pyvista==0.41.1
      - pyvistaqt==0.0.0
      - pyxdg==0.28
      - qdarkstyle==3.1
      - qstylizer==0.2.2
      - qtawesome==1.2.3
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - referencing==0.30.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rope==1.9.0
      - scooby==0.7.2
      - seaborn==0.12.2
      - send2trash==1.8.2
      - setuptools==68.0.0
      - sgqlc==16.3
      - six==1.16.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.3.2.post1
      - sphinx==7.0.1
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - tabulate==0.9.0
      - terminado==0.17.1
      - text-unidecode==1.3
      - textdistance==4.5.0
      - threadpoolctl==3.2.0
      - three-merge==0.1.1
      - tifffile==2023.7.18
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.11.8
      - toolz==0.12.0
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - typing-utils==0.1.0
      - tzdata==2023.3
      - unidecode==1.3.6
      - urllib3==2.0.4
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - whatthepatch==1.0.5
      - wheel==0.41.0
      - widgetsnbextension==4.0.8
      - wslink==1.11.1
      - xarray==2025.4.0
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - yapf==0.33.0
      - zipp==3.16.2
prefix: /home/rl05/.conda/envs/mne1.4.2
